
package client.artefact;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "MethodsService", targetNamespace = "http://main/", wsdlLocation = "http://127.0.0.1:8180/PhasebookMainWS/Methods?wsdl")
public class MethodsService
    extends Service
{

    private final static URL METHODSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(client.artefact.MethodsService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = client.artefact.MethodsService.class.getResource(".");
            url = new URL(baseUrl, "http://127.0.0.1:8180/PhasebookMainWS/Methods?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8180/PhasebookMainWS/Methods?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        METHODSSERVICE_WSDL_LOCATION = url;
    }

    public MethodsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MethodsService() {
        super(METHODSSERVICE_WSDL_LOCATION, new QName("http://main/", "MethodsService"));
    }

    /**
     * 
     * @return
     *     returns Methods
     */
    @WebEndpoint(name = "MethodsPort")
    public Methods getMethodsPort() {
        return super.getPort(new QName("http://main/", "MethodsPort"), Methods.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Methods
     */
    @WebEndpoint(name = "MethodsPort")
    public Methods getMethodsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://main/", "MethodsPort"), Methods.class, features);
    }

}
